image: node:18

pipelines:
  branches:
    main:
      - step:
          name: Build and Test Full Stack
          caches:
            - node
          script:
            - cd server
            - npm install
            - npx prisma generate
            - npm run build
            - cd ../client
            - npm install
            - npm run build
          artifacts:
            - client/dist/**
            - server/dist/**
